import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd(),sourceDir=join(root,'preview'),outDir=join(sourceDir,'dist');
function parseCsv(source){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<source.length;i+=1){const ch=source[i];if(quoted){if(ch==='"'&&source[i+1]==='"'){value+='"';i+=1;}else if(ch==='"')quoted=false;else value+=ch;continue;}if(ch==='"')quoted=true;else if(ch===','){row.push(value);value='';}else if(ch==='\n'){row.push(value.replace(/\r$/,''));rows.push(row);row=[];value='';}else value+=ch;}if(value||row.length){row.push(value.replace(/\r$/,''));rows.push(row);}const [headers,...records]=rows.filter(entry=>entry.some(Boolean));return records.map(record=>Object.fromEntries(headers.map((header,index)=>[header,record[index]??''])));}
function copyDir(from,to){mkdirSync(to,{recursive:true});for(const name of readdirSync(from)){const src=join(from,name),dest=join(to,name);if(statSync(src).isDirectory())copyDir(src,dest);else copyFileSync(src,dest);}}
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]);
const brandAssets=JSON.parse(readFileSync(join(sourceDir,'image-assets.json'),'utf8'));
const rawProducts=parseCsv(readFileSync(join(root,'data/sample-products.csv'),'utf8'));
const products=rawProducts.map((row,index)=>({id:row['URL handle'],title:row.Title,description:row.Description,species:row['product.metafields.plant.species'],price:Number(row.Price),inventory:Number(row['Inventory quantity']),light:row['product.metafields.plant.light'],watering:row['product.metafields.plant.watering'],soil:row['product.metafields.plant.soil'],growingConditions:row['product.metafields.plant.growing_conditions'],difficulty:row['product.metafields.plant.difficulty'],humidity:row['product.metafields.plant.humidity'],matureSize:row['product.metafields.plant.mature_size'],petSafety:row['product.metafields.plant.pet_safety'],careNotes:row['product.metafields.plant.care_notes'],imageUrl:brandAssets.products[row['URL handle']]||'',artVariant:index%5}));
const missing=products.filter(product=>!product.imageUrl);if(missing.length)throw new Error('Missing representative image for: '+missing.map(item=>item.id).join(', '));
rmSync(outDir,{recursive:true,force:true});mkdirSync(outDir,{recursive:true});
for(const file of ['styles.css','brand-refresh.css','app.js','config.js','image-assets.js'])copyFileSync(join(sourceDir,file),join(outDir,file));
copyDir(join(sourceDir,'admin'),join(outDir,'admin'));
const sourceHtml=readFileSync(join(sourceDir,'index.html'),'utf8');
const embeddedProducts=`<script>window.__LIL_ROBB_PRODUCTS__ = ${JSON.stringify(products).replace(/</g,'\\u003c')};</script>`;
writeFileSync(join(outDir,'index.html'),sourceHtml.replace('<!--PRODUCT_DATA-->',embeddedProducts));
writeFileSync(join(outDir,'products.json'),JSON.stringify(products,null,2)+'\n');writeFileSync(join(outDir,'.nojekyll'),'');
const noticeHtml=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Robb Store — Image notice</title><link rel="stylesheet" href="./styles.css"><link rel="stylesheet" href="./brand-refresh.css"></head><body><main class="credits-page"><img class="footer-logo" src="${escapeHtml(brandAssets.logo)}" alt="The Robb Store"><p class="eyebrow">Product photography</p><h1>Image notice</h1><p>${escapeHtml(brandAssets.disclosure)}</p><p>The launch catalog uses representative stock-style images to help shoppers identify each plant type. When actual inventory photography is available, it can replace these examples from the owner console or Shopify.</p><p><a class="button secondary" href="./">Back to the store</a></p></main></body></html>`;
writeFileSync(join(outDir,'photo-credits.html'),noticeHtml);
console.log(`Built The Robb Store preview with ${products.length} products and ${Object.keys(brandAssets.products).length} representative plant images.`);
